services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=webquiz'
      - 'POSTGRES_USER=webquiz'
      - 'POSTGRES_PASSWORD=webquiz'
    ports:
      - '5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U webquiz -d webquiz']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata:
