services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=webquiz'
      - 'POSTGRES_USER=webquiz'
      - 'POSTGRES_PASSWORD=webquiz'
    ports:
      - '5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata:
