spring.application.name=WebQuiz

server.port=8080
management.endpoints.web.exposure.include=health,info
management.endpoint.shutdown.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
